server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:

      # USER-SERVICE
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**

        # FAVOURITE-SERVICE
        - id: favourite-service
          uri: lb://FAVOURITE-SERVICE
          predicates:
            - Path=/api/favourites/**

        # INVENTORY-SERVICE
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**


        # ORDER-SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        # PAYMENT-SERVICE
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**

        # SHIPPING-SERVICE
        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/shipping/**

        # NOTIFICATION-SERVICE
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

        # PRODUCT-SERVICE
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**

        # PROMOTION-SERVICE
        - id: promotion-service
          uri: lb://PROMOTION-SERVICE
          predicates:
            - Path=/api/promotions/**

        # PROXY-CLIENT
        - id: proxy-client
          uri: lb://PROXY-CLIENT
          predicates:
            - Path=/api/proxy/**

        # RATING-SERVICE
        - id: rating-service
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/ratings/**

        # SEARCH-SERVICE
        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/api/search/**

        # TAX-SERVICE
        - id: tax-service
          uri: lb://TAX-SERVICE
          predicates:
            - Path=/api/tax/**

        # SWAGGER DOC ROUTES
        - id: user-service-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v3/api-docs/user-service

        - id: favourite-service-docs
          uri: lb://FAVOURITE-SERVICE
          predicates:
            - Path=/v3/api-docs/f

        - id: inventory-service-docs
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/v3/api-docs/inventory-service

        - id: order-service-docs
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v3/api-docs/order-service

        - id: payment-service-docs
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/v3/api-docs/payment-service

        - id: shipping-service-docs
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/v3/api-docs/shipping-service

        - id: notification-service-docs
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/v3/api-docs/notification-service

        - id: product-service-docs
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v3/api-docs/product-service

        - id: promotion-service-docs
          uri: lb://PROMOTION-SERVICE
          predicates:
            - Path=/v3/api-docs/promotion-service

        - id: proxy-client-docs
          uri: lb://PROXY-CLIENT
          predicates:
            - Path=/v3/api-docs/proxy-client

        - id: rating-service-docs
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/v3/api-docs/rating-service

        - id: search-service-docs
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/v3/api-docs/search-service

        - id: tax-service-docs
          uri: lb://TAX-SERVICE
          predicates:
            - Path=/v3/api-docs/tax-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    root: INFO

# Spring doc OpenAPI Swagger Configuration
springdoc:
  swagger-ui:
    urls:
      - name: User Service - Auth
        url: /v3/api-docs/user-service
#        url: /v3/api-docs/user-service
      - name: Favourite Service
        url: /v3/api-docs/f
      - name: Inventory Service
        url: /v3/api-docs/inventory-service
      - name: Order Service
        url: /v3/api-docs/order-service
      - name: Payment Service
        url: /v3/api-docs/payment-service
      - name: Shipping Service
        url: /v3/api-docs/shipping-service
      - name: Notification Service
        url: /v3/api-docs/notification-service
      - name: Product Service
        url: /v3/api-docs/product-service
      - name: Promotion Service
        url: /v3/api-docs/promotion-service
      - name: Proxy Client
        url: /v3/api-docs/proxy-client
      - name: Rating Service
        url: /v3/api-docs/rating-service
      - name: Search Service
        url: /v3/api-docs/search-service
      - name: Tax Service
        url: /v3/api-docs/tax-service
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
