#server:
#  port: 8081
#spring:
#  application:
#    name: USER_SERVICE
#
##api:
##  gateway:
##    url: http://localhost/8080
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method
#    tagsSorter: alpha
#  default-produces-media-type: application/json webflux:

